services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trinity_db
      POSTGRES_USER: trinity_user
      POSTGRES_PASSWORD: trinity_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - trinity-net

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - trinity-net

  redis:
    image: redis:7
    networks:
      - trinity-net

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - trinity-net

  celery:
    build: .
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      - trinity-net

  fastapi:
    build: .
    command: uvicorn apps.fastapi_app:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - trinity-net

volumes:
  postgres_data:
  mongo_data:

networks:
  trinity-net:
